# frozen_string_literal: true

# The seeding pipeline carries the legacy `wp_terms.term_id` onto Classification::Term
# (T-06). Unlike post ids — masked as `<ID>` by the parity normalizer — term ids are
# LITERAL bytes of the golden screens: get_body_class() emits `tag-6` / `category-3`
# (wp-includes/post-template.php:761,769), and the page-list block compares
# `get_queried_object_id() === $page->ID` raw (wp-includes/blocks/page-list.php:283),
# an id collision the oracle's corpus makes observable (term 2 'top-category' vs page 2
# 'sample-page' marks Sample Page `current-menu-item` on the category archive).
#
# `GENERATED ALWAYS` rejects the explicit id at INSERT; `BY DEFAULT` accepts it while
# keeping the sequence for rows created without one. The pipeline realigns the sequence
# (reset_pk_sequence!) after loading, so ordinary inserts cannot collide.
class TermsIdGeneratedByDefault < ActiveRecord::Migration[8.1]
  def up
    execute "ALTER TABLE terms ALTER COLUMN id SET GENERATED BY DEFAULT"
  end

  def down
    execute "ALTER TABLE terms ALTER COLUMN id SET GENERATED ALWAYS"
  end
end
