import { chromium } from "playwright";
const b = await chromium.launch();
const c = await b.newContext({ baseURL:"http://127.0.0.1:3100", viewport:{width:1440,height:1000} });
const p = await c.newPage();
const api=[]; const errs=[];
p.on('response', r=>{ const u=r.url(); if(u.includes('/wp-json/')) api.push(`${r.status()} ${r.request().method()} ${decodeURIComponent(u.replace(/^https?:\/\/[^/]+/,'').split('?')[0])}`); });
p.on('pageerror', e=>errs.push(String(e).split('\n')[0].slice(0,140)));
await p.goto("/login"); await p.fill('input[name="log"]','oracle_admin'); await p.fill('input[name="pwd"]','oracle-admin-pw');
await p.check('input[name="testcookie"]').catch(()=>{});
await Promise.all([p.waitForLoadState('networkidle'), p.click('button[type=submit],input[type=submit]')]);
await p.goto("/console/site-editor", {waitUntil:'domcontentloaded'});
await p.waitForTimeout(15000);
console.log("edit-site skeleton:", await p.locator('.edit-site, .interface-interface-skeleton, .edit-site-layout').count());
console.log("sidebar nav items:", await p.locator('.edit-site-sidebar-navigation-item, .edit-site-layout__sidebar a, nav a').count());
const bad = [...new Set(api)].filter(a=>!a.startsWith('200'));
console.log("non-200 API calls:", bad.length ? bad.join(" | ") : "(none)");
if (errs.length) console.log("errors:", [...new Set(errs)].slice(0,4).join(" | "));
await p.screenshot({path:"/tmp/se_gb.png"});
await b.close();
