import { chromium } from "playwright";
const b = await chromium.launch(); const c = await b.newContext({ baseURL: "http://127.0.0.1:3100", viewport: { width: 1300, height: 860 } });
const p = await c.newPage();
await p.goto("/login"); await p.fill('input[name="log"]',"island_e2e"); await p.fill('input[name="pwd"]',"island-pw-1");
await p.check('input[name="testcookie"]').catch(()=>{}); await Promise.all([p.waitForLoadState("networkidle"), p.click('button[type=submit],input[type=submit]')]);
await p.goto("/console/site-editor"); await p.waitForSelector("#site-editor-root .se-app",{timeout:15000});
await p.locator(".se-sidebar .se-item").first().click(); await p.waitForSelector(".se-main .be-canvas",{timeout:8000});
await p.locator(".se-main .be-block").first().click(); await p.waitForTimeout(400);
await p.screenshot({ path: "/tmp/site_editor.png", fullPage: false });
console.log("SHOT1_OK");
await p.click('.se-nav:has-text("Styles")'); await p.waitForSelector(".se-styles",{timeout:8000}); await p.waitForTimeout(400);
await p.screenshot({ path: "/tmp/site_editor_styles.png", fullPage: false });
console.log("SHOT2_OK"); await b.close();
